name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up headless browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Run HTML test
        run: |
          chromium-browser --headless --disable-gpu --no-sandbox index.test.html
